### ISSUE TITLE
Unable to import solution for SIGMOD2021

### ISSUE THREAD

**Issue by jerrylususu** [HPI-Information-Systems/snowman#91]
I am working on a SIGMOD2021 solution, yet it seems the program refuses to take in a `output.csv` solution file generated for the toy dataset (dataset 1). I tried `pliot` and `sigmod2021` format yet it still gives out errors. No idea what is happening. Expecting the result to be imported normally. The `output.csv` file is attached.

Version info:
- OS: Windows 10 20H2
- Snowman: v1.1.2, Local instance

![image](https://user-images.githubusercontent.com/17522475/111209517-2af68e00-85dd-11eb-8103-59530ce2aa73.png)

![image](https://user-images.githubusercontent.com/17522475/111209987-bcfe9680-85dd-11eb-8f3a-df4e982dfd51.png)

![image](https://user-images.githubusercontent.com/17522475/111209997-c0921d80-85dd-11eb-8115-80b9b018d75f.png)

[output.zip](https://github.com/HPI-Information-Systems/snowman/files/6143971/output.zip)

**Comment by Lasklu** [comment]
Hi @jerrylususu 
thank you for your feedback! The issue behind this is that we have mistakenly required a column "label" in the result-file schema. 
If this column did not exist in the resultfile, our api had thrown an exception. We fixed this and created the latest release: [v1.1.3](https://github.com/HPI-Information-Systems/snowman/releases/tag/v1.1.3) (you can directly download it). It should then work.

Feel free to contact us if you have any further comments, feature requests or questions!

Regards,
Lukas

**Comment by jerrylususu** [comment]
Thanks for this quick response. By the way, it seems that you forgot bump the version number for the artifacts.

**Comment by phpfs** [comment]
@jerrylususu Thanks for the hint here - we didn't raise the version in all three package.json files - but it is fixed now :)
